version: 2
jobs:
  build:
    branches:
      only:
        - v3.0
    docker: # use the docker executor type; machine and macos executors are also supported
     - image: circleci/node:10.15.3
    steps:
      - checkout # check out the code in the project directory
      - run:
          command: >
            sudo curl https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - &&
            sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' &&
            sudo apt-get update &&
            sudo apt-get install -y google-chrome-stable build-essential jq git openssh-server
      - run:
          command: >
            sudo wget https://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip &&
            sudo unzip chromedriver_linux64.zip &&
            sudo mv chromedriver /usr/bin/chromedriver &&
            sudo chmod +x /usr/bin/chromedriver &&
            sudo rm chromedriver_linux64.zip &&
            cd $HOME/project &&
            npm install &&
            npm test